[project]
name = "restoring-ancient-russian-texts"
version = "0.1.0"
description = "Restoring old russian texts from 11 to 17 century (Masked language modelling)"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Alex", email = "alexandersychev2005@gmail.com" },
    { name = "Yura", email = "Ecsport00@gmail.com"}
]

dependencies = [
    "datasets>=2.19.0",
    "huggingface-hub",
    "tokenizers>=0.19.1",
    "torch",
    "transformers>=4.44.2",
    "fastapi",
    "uvicorn",
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
    "torch==2.10.0+cu126",
    "torchvision==0.25.0+cu126",
    "torchaudio==2.10.0+cu126",
    "beautifulsoup4>=4.14.3",
    "pandas>=3.0.1",
    "requests>=2.32.5",
    "lxml>=6.1.0",
    "protobuf>=7.34.1",
    "accelerate>=1.13.0",
    "evaluate>=0.4.6",
    "jiwer>=4.0.0",
    "tqdm>=4.67.3",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[tool.uv]
package = false

